[package]
name = "dedupe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "0.5.5"
walkdir = "2.3.2"
indicatif = {version = "*", features = ["rayon"]}